CREATE TABLE Person (
                        person_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL UNIQUE,
                        age int check ( age > 0 ) NOT NULL
);

CREATE TABLE Book (
                      book_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL,
                      person_id int REFERENCES Person(person_id) ON DELETE SET NULL
);